### ISSUE TITLE
"Hacker" flag in social profile, but account not banned.

### ISSUE THREAD

**Issue by GreatCheat** [hrt/KrunkerMultihack#20]
These people who tried to use your cheat in latest version, got their public accounts flagged as "HACKER". They're still not banned, but they may be one day.

Is there anything that You can do to roll back that "HACKER" flag?

Here's how does it look:

https://ibb.co/TTQ9dBy

**Comment by hrt** [comment]
Can you send me a link or full screenshot of a social account that has this? My blatant account that I've used for developing and testing the cheats are not classed as "hacker".

Are you sure it's not from other cheats you've used in the past or manual

![image](https://user-images.githubusercontent.com/21159953/62542120-cb6cc400-b878-11e9-9fa2-9cfc9f7ed8bf.png)

**Comment by hrt** [comment]
Also I doubt this flag you have is revertible since it's server sided and there goes a saying "once a cheater, always a cheater" 😂

**Comment by GreatCheat** [comment]
For example this guy:

https://krunker.io/social.html?p=profile&q=Talking123

I found out that HACKER tag reduces damage done by all of your weapons by 75% :)

**Comment by hrt** [comment]
@GreatCheat Thanks for the info but unfortunately I can't say my cheat is causing this when none of my accounts have this flag yet:

https://krunker.io/social.html?p=profile&q=phoon007
https://krunker.io/social.html?p=profile&q=HackVsHack
https://krunker.io/social.html?p=profile&q=hrt/HeroHunter

Even if my accounts got flagged I still wouldn't be sure it's caused by my own cheat since I've posted my accounts publicly.

This flag is probably set manually or some other way.

![image](https://user-images.githubusercontent.com/21159953/62578672-5b356100-b8bf-11e9-825d-f095a329dbc5.png)
![image](https://user-images.githubusercontent.com/21159953/62578681-625c6f00-b8bf-11e9-886d-6aca3b12704d.png)

**Comment by GreatCheat** [comment]
Maybe You're right. I guess some accounts got flagged manually because of reports/complaints that other players send /w video evidence to moderators or developers.

**Comment by hrt** [comment]
@GreatCheat We will have to see
